### PR TITLE
FIX: correctly add `restrict_replies_bypass_groups` param to the permitted list.

### PR DESCRIPTION
**Pull request by vinothkannans**

### CODE REVIEW

**Review by CvX — APPROVED** [review]

**Review by ZogStriP — CHANGES_REQUESTED** [review]
I'm not sure I understand what issue this is solving? What's not working? 🤔 

I'm also a bit scared of the use of `to_unsafe_h` which I've never seen before.

**Comment by vinothkannans** [comment]
> I'm also a bit scared of the use of to_unsafe_h which I've never seen before.

[`params.to_h`](https://apidock.com/rails/v5.2.3/ActionController/Parameters/to_h) will work only if those params are permitted already using `params.permit(:name)`. Else it will return the `UnfilteredParameters` error. On other hand, [`to_unsafe_h`](https://apidock.com/rails/v5.2.3/ActionController/Parameters/to_unsafe_h) will convert the params to hash even if it's not permitted.

The values we added dynamically don't have the `permitted` flag after the `super` method execution.

**Comment by vinothkannans** [comment]
https://meta.discourse.org/t/500-error-when-saving-category-security-settings/231055

Here is the context of the error. We were unable to [add groups to `restrict_replies_bypass_groups` param](https://github.com/discourse/discourse-restricted-replies/pull/37/files#diff-040b0c3e0e3b0c377ccb9da72d51e1a9716135b8958e74aa81f104651972ee23L43) directly.

**Comment by ZogStriP** [comment]
> The values we added dynamically don't have the `permitted` flag after the `super` method execution.

So you're saying [this line](https://github.com/discourse/discourse/blob/6df36247c1d2f97d257eb9ec08f50d8709d0159d/app/controllers/categories_controller.rb#L374) doesn't work?

**Comment by vinothkannans** [comment]
@ZogStriP yes, it's not working if the custom field is array.

**Comment by ZogStriP** [comment]
Interesting 🤔 In that case, I thing we should provide an API in core to allow for plugins to "permit" custom_fields directly in the `category_params` method rather than having plugin overwrite that method.

**Comment by vinothkannans** [comment]
@ZogStriP I find a way to include array-type custom fields without a plugin API.

**Review by ZogStriP — APPROVED** [review]

**Comment by ZogStriP** [comment]
Make sure you add a proper commit message when merging this. It should link to the commit in core to explain why the change works that way.

**Comment by pmusaraj** [comment]
Are spec failures here relevant @vinothkannans ?

**Comment by vinothkannans** [comment]
@pmusaraj the specs were failing because of the other PR which this one depends on not merged. Now all the checks have passed.

**Pull request merged**
